### ISSUE TITLE
plot.neigh no displaying cell neighborhoods 

### ISSUE THREAD

**Issue by mmeziane1** [gstlearn/gstlearn#100]
Hello, 

It appears that plot.neigh encounters a problem while trying to display a cell neighborhood. In the following code : 

library("gstlearn")
grid = DbGrid_create(nx = c(10,10),
                     dx=c(0.1, 0.1))
neigh = NeighCell_create(FALSE, 1)
ggDefaultGeographic()+
  plot.neigh(neigh, grid)

when running the final line, the following message is returned : 

Erreur dans validObject(.Object) : 
  invalid class “MethodWithNext” object: Error : C stack usage  7969540 is too close to the limit.

**Comment by fabien-ors** [comment]
Thank you for reporting.
Fix will be available in next release (#101).
