### ISSUE TITLE
Rename VectorHelper::multiplyConstant() and VectorHelper::multiplyConstantInPlace()

### ISSUE THREAD

**Issue by remi-moyen** [gstlearn/gstlearn#105]
`VectorHelper::multiplyConstant()` and `VectorHelper::multiplyConstantInPlace()` behave in the opposite way to what their names imply:

`VectorHelper::multiplyConstant()` modifies its input vector, while `VectorHelper::multiplyConstantInPlace()` does not modify the input and instead has a `vecout` output argument.

Note that several other functions in `VectorHelper` have the same issue, for example `addInPlace(const VectorDouble &, const VectorDouble &, VectorDouble &, int)`.

I started making this change but then I wondered if this wasn't in part by design and thus decided to open an issue to discuss this first. For me "in place" implies that the input vector is modified but maybe it should be read as "the vector to modify is passed as argument" (as opposed to "a new vector is returned", see for example `add()` vs. `addInPlace()`).

If that is the case then there is still an issue with `multiplyConstant()` which definitely is "in place" (with both ways of understanding "in place"), but maybe not `multiplyConstantInPlace()`, `addInPlace()` etc.

**Comment by remi-moyen** [comment]
See branch [VH_multiplyConstantInPlace](https://github.com/gstlearn/gstlearn/tree/VH_multiplyConstantInPlace) for a suggested fix, assuming that my understanding of "in place" is correct.

**Comment by remi-moyen** [comment]
Hi Didier,

I understand your idea, and I also had the same thought as you when reading all the function names (rather than just the 2 I mentioned in the title of this issue). And it does make sense -- I know very well the problem of optimisation and allocating a new object to return it being costly! Your logic makes sense.

I don't think you need to change all the names just to please me ;-)

Still, the function `VectorHelper::multiplyConstant()` is still incorrectly named since it modifies one of its arguments (which is your definition of "in place"). I suggest renaming it to `VectorHelper::multiplyConstantInPlace()`. You would then have 2 functions with the same name but different lists of arguments, which is perfectly fine and also what you do for many other functions in this class, so I don't think that's an issue.

I will update the branch I made for this and add a merge request, if that's OK for you.

The same issue happens for `divideConstant()` and `addConstant()` which I think should also be renamed, just for the sake of the overall consistency. Maybe also `copy()` although these are slightly different operations so maybe it's OK this way.

On the longer term, maybe something more needs to be done, but this is mostly cosmetic, so that's probably not very important.

**Comment by drenard77810** [comment]
Hi Remi
Just before you modify your branch and provoke a PR...
I slightly correct your point about having two functions with same name and different arguments.
As a rule, this should be avoided... In fact SWIG is not very clever and, when this happens, the prototype chosen by swig is random (I think). As a result, one of the two prototypes can never be reached in Python (say).
So, I usually decide to modify the name of one of the two functions in order to avoid this issue.
Of course renaming a function is ... quite dangerous, as we have to warn all the potential users.
But this is life and progress.
Thanks for your help.

**Comment by drenard77810** [comment]
Hi Remi

We now have a clear point-of-view on the method with name "InPlace".
The main reason is that they AVOID TO PERFORM ANY ALLOCATION. Hence they are appreciated when looking for time performance!!!
They can be used (for addition procedure) with the following prototypes:

void addInPlace(const double& a, const double& b , double& result)
{
  result = a + b
}

or
void addInPlace(const double& a, double& b)
{
   b = a + b
}

Note that no difference is made in terms of names. Possibly, in the future, we can imagine to make a distinction.

Another possibility could be to add to 'this'.

void ValueStorage::addInPlace(const double& a)
{
   _storedValue += a
}

Then the function should note be called "InPlace" anymore. I try to look for such wrong name but could not find any (fortunately).

The last concern is the rank of the modified argument (in the case of "inPlace" genuine function) among the list of arguments. This is not clear at current time. The current ordering (which is not systematic) is as follows:
1) context arguments (readonly)
2) the modified argument
3) the remaining arguments which can be defaulted (they all have a default value therefore)

Therefore the position of the "modified" argument is lost in the middle of a series of other arguments and is not very evident in general (although it should be distinguished by not being "const"). We could imagine to put it systematically in first argument position. But:
- not sure this convention is acceptable (not applied in third-party libraries for example)
- would require a lot of work (currently 419 calls currently of "InPlace" methods).

I consider that this issue can be closed. Do not hesitate to re-open it if you have some more thoughts.
Cheers
