### ISSUE TITLE
Model$reduce with known means

### ISSUE THREAD

**Issue by xfreulon** [gstlearn/gstlearn#117]
Using the method **reduce**  on a Second Order Stationary model (the means are known) does not keep the mean value.

Example in R for a bivariate model:

> mod_Z_SOS$getMeans()
[1] 1 2  # Means of the two variables are respectively 1 and 2
> mod_Z1_SOS = mod_Z_SOS$reduce(0) # we get the model of the first variable
> mod_Z1_SOS$getMeans()
[1] 0 # the model is Second Order Stationary but the reported mean is 0; it should be 1 (the initial mean of the first variable).

**Comment by xfreulon** [comment]
Model$reduce creates a new model but Vario$reduce modifies the current variogram. It seems to me a bit awkward

Starting from a bivariate model **mod_Z** and bivariate variogram **var_Z**, to visualize the variogram fit of the first variable I have to do:

> var_Z1 = var_Z$clone()
> err = var_Z1$reduce(varcols = 0, dircols = 0)
> multi.varmod(var_Z1, mod_Z_IRF0$reduce(0))

I would expect to be able to do

> multi.varmod(var_Z$reduce(0,0),  mod_Z_IRF0$reduce(0))

**Comment by drenard77810** [comment]
On the first part, the bug has been fixed as shown in the following test (written in Python):

import gstlearn as gl

nvar = 2
ndim = 3
model = gl.Model(nvar, ndim)

model.addCovFromParam(gl.ECov.NUGGET,sills=[1,0,0,3])
model.setMeans([-2, 4])
model.display()

mod2 = model.reduce([1])
mod2.display()

The corresponding output:
Model characteristics
=====================
Space dimension              = 3
Number of variable(s)        = 2
Number of basic structure(s) = 1
Number of drift function(s)  = 0
Number of drift equation(s)  = 0

Covariance Part
---------------
Nugget Effect
- Sill matrix:
               [,  0]    [,  1]
     [  0,]     1.000     0.000
     [  1,]     0.000     3.000
Total Sill
               [,  0]    [,  1]
     [  0,]     1.000     0.000
     [  1,]     0.000     3.000

Known Mean(s)    -2.000     4.000
 
Model characteristics
=====================
Space dimension              = 3
Number of variable(s)        = 1
Number of basic structure(s) = 1
Number of drift function(s)  = 0
Number of drift equation(s)  = 0

Covariance Part
---------------
Nugget Effect
- Sill         =      3.000
Total Sill     =      3.000
Known Mean(s)     4.000

**Comment by drenard77810** [comment]
Concerning of homogeneity of "reduce" method...
A generic function has been created with prototype:
  Class* Class::createdReduce(args)
This method, starting from an input object of type "Class", returns a pointer to an allocated new object of the same class, after a reduction has been applied. This has been carried on for Db, Vario, Model, CovContext, ACovAnisolist, CovAniso, ...

For some classes, an 'inplace" version is also available. For better legibility, thoses functions have been renamed into "resetReduce", with prototype

void (or in() Class::resetReduce(args).
