### ISSUE TITLE
Backup issue : crash when using namconv in migrate*

### ISSUE THREAD

**Issue by fabien-ors** [gstlearn/gstlearn#145]
From @tromary 
I thought namconv was the new name of RGeostats "radix" but when putting namconv ="" in a migrate command (so as to avoid to have attributes named Migrate.*) it crashes

**Comment by fabien-ors** [comment]
Output naming convention in migrate* functions has been fixed.

**Comment by pierre-guillou** [comment]
The following SWIG typemap (in `r/rgstlearn.i`) should help to convert automatically R strings to NamingConvention instances:

```swig
%typemap(scoercein) NamingConvention, NamingConvention &, const NamingConvention, const NamingConvention & %{
  if (typeof($input) == "character") $input = NamingConvention($input);
  if (inherits($input, "ExternalReference")) $input = slot($input,"ref");
%}

```

**Comment by fabien-ors** [comment]
Fixed in dev branch.
