### ISSUE TITLE
gstlearn 1.2.1 for R On windows

### ISSUE THREAD

**Issue by SKNo** [gstlearn/gstlearn#170]
Hello
I tried to install gstlearn 1.2.1 for R (4.4.0) on Windows using
`install.packages("gstlearn",repos="https://soft.mines-paristech.fr/cran")`

But the installation failed:
```
trying URL 'https://soft.mines-paristech.fr/cran/src/contrib/gstlearn_1.2.1.tar.gz'
Content type 'application/x-gzip' length 18159897 bytes (17.3 MB)
downloaded 17.3 MB

* installing *binary* package 'gstlearn' ...
Warning in system(paste("cp -R .", shQuote(instdir), "|| (", TAR, "cd - .| (cd",  :
  'cp' not found
ERROR: installing binary package failed
* removing 'E:/Logiciel/R/R_Classic/R-4.4.0/library/gstlearn'

The downloaded source packages are in
        ‘C:\LOCAL\TEMP\RtmpwpRZCE\downloaded_packages’
Warning message:
In install.packages("gstlearn", repos = "https://soft.mines-paristech.fr/cran") :
  installation of package ‘gstlearn’ had non-zero exit status
```
After inspecting the dowloaded package, I noticed that install.package() tries to install linux version on windows (package contains only gstlearn.so not gastlearn.dll). 
Could you please advise me,
Thank you

**Comment by fabien-ors** [comment]
Thank you for your feedback.
gstlearn v1.2.2 has been delivered just now.
The R package for windows should now support R v4.4.0.
Please confirm :)

**Comment by SKNo** [comment]
Thank you 
Okay, please let me know when it is the right time to dowload and to test.

**Comment by fabien-ors** [comment]
In fact, there is an issue with the python package, not the R package.
Here is the compatibility matrix for the R package.
https://github.com/gstlearn/gstlearn/actions/runs/9255370745
Could you try please ?

**Comment by SKNo** [comment]
I have successfully installed gstlearn 1.2.2 for R 4.4.0 on Windows. Simple tests shows that everything is working correctly. Later, I will check with more complicated R-scripts and if there are any problem I will let you know here
Thank you again

**Comment by fabien-ors** [comment]
Great!
I close the issue. Than you for reporting!

Note: gstlearn 1.2.3 is currently publishing.
No new feature except that this new version will work for R and python! (I hope so ^_^)
