### ISSUE TITLE
Db::createReduce

### ISSUE THREAD

**Issue by NDesassis** [gstlearn/gstlearn#202]
When using  createReduce with a DbGrid argument and using ranks, the newly created Db (which is not a DbGrid anymore) has no coordinates.

**Comment by drenard77810** [comment]
When the input file is a DbGrid, then the coordinates may be implicit (they do not correspond to attributes contained in the Db). When reducing this Db, the resulting file is ALWAYS a Db (no more grid oriented). Then this new Db has no coordinate.

This bug has been fixed.

Specific attributes are created on the fly in the latter case and glued to the output Db;
