### ISSUE TITLE
Wrong CMake variable name used to detect Eigen

### ISSUE THREAD

**Issue by remi-moyen** [gstlearn/gstlearn#235]
`cpp.cmake` has this code:
https://github.com/gstlearn/gstlearn/blob/9261746d491908c81ddcfc9dd1ec5802b644393e/cmake/cpp.cmake#L75-L76

This code has two minor issues:
- First, `EIGEN3_FOUND` should be replaced by `Eigen3_FOUND` as CMake is case-sensitive in variable names and the package is named Eigen3 (not EIGEN3). This doesn't matter as the test is just to print a message, but it makes things confusing as it looks like Eigen is not found (the message is not printed) even though it actually is.
- Second, the message shouldn't mention `${EIGEN3_INCLUDE_DIR}` as this variable is not defined, and also defining it is not needed (line 138 later links with `Eigen3::Eigen` which is enough to get the correct include directories set, according to [Eigen's doc](https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html)).

I suggest to replace the two lines above by something like:
```cmake
if(Eigen3_FOUND) 
    message(STATUS "Found Eigen3 version ${Eigen3_VERSION} in ${Eigen3_DIR}")
```

**Comment by fabien-ors** [comment]
Good point ! Thank you Rémi.
Do you want to make a Pull Request or do you want me to do it for you?

**Comment by remi-moyen** [comment]
If you don't mind, I'd rather you do it. I'm not fully confident of my handling of git and github branching, merging, pull requests etc. so for something that's a 2-lines copy-paste it's probably far quicker if you do it directly!

Thanks!

(sorry, I'm trying to learn...)

**Comment by fabien-ors** [comment]
Done in addbf89
