### ISSUE TITLE
Model::createFromParam

### ISSUE THREAD

**Issue by NDesassis** [gstlearn/gstlearn#243]
The argument **sills** should be a MatrixSquareSymmetric instead of VectorDouble for a better ergonomics.
If the modifications is performed, check that we can still pass a float from python (i.e float is transformed into a MatrixSquareSymmetric by Swig typemap).

The same for Model::addCovFromParam.

Best.

**Comment by fabien-ors** [comment]
I understand that you are talking about the following methods: (a) Model::addCovFromParam, (b) Model::createFromParam, or (c) CovAniso::setSill. Could you confirm ?
If so, all these methods already handle single sill vs sills matrix using :
- two different arguments for (a) and (b) or
- by overriding for (c)

What kind of native Python type would you be able to automatically convert to MatrixSquareSymmetric ?
Example:
1. `model.addCovFromParam(gl.ECov.SPHERICAL, range=40., sills=[[0.7, 0.3][0.3,0.7]])`
2. `model.addCovFromParam(gl.ECov.SPHERICAL, range=40., sills=np.matrix('0.7 0.3; 0.3 0.7'))`
3. `model.addCovFromParam(gl.ECov.SPHERICAL, range=40., sills=np.array([[0.7, 0.3][0.3,0.7]]))`

Same question for R language.
Thx

**Comment by drenard77810** [comment]
This is now fixed... and uses the new TYPEMAP converting a Matrix from python (numpy.array) or R (matrix) int Matrix internal gstlearn format.
