### ISSUE TITLE
IDE (e.g. Visual Studio) does not list header files

### ISSUE THREAD

**Issue by remi-moyen** [gstlearn/gstlearn#255]
Currently in Visual Studio (and presumably in other IDEs as well, given how I solved the problem), the header files are not listed in the project tree. They are correctly found when compiling or when going to where a symbol is defined, but they are not seen as being part of the project (they are seen as an external dependency instead).

This means they are not listed directly, but also that e.g. searching for "all uses" of a symbol does not search them, so this is definitely not very convenient.

The root cause is that the headers are not passed to the `add_library()` call in CMake (see e.g. [this](https://stackoverflow.com/questions/13703647/how-to-properly-add-include-directories-with-cmake) for details).

The solution is to do the same as for the source files: add a new file in `include/` that lists all the headers (I followed the same rule as in `all_sources.cmake` and listed the files rather than using `GLOB` -- I generated this file automatically by adding all `*.h*` files so hopefully it's not missing anything?), and in `cpp.cmake` add the content of this file to the `${SOURCES}` variable.

**Comment by fabien-ors** [comment]
I confirm that headers are not listed in Visual Studio (or Code::Blocks) projects generated by CMake. On the other hand, there is no problem while using VS Code or Eclipse CDT. The reason is explained in this answer:
https://stackoverflow.com/questions/13703647/how-to-properly-add-include-directories-with-cmake/74409439#74409439
I am not an expert of Visual Studio, but is there any plugin in Visual Studio that offer the possibility to handle CMake project (gstlearn is a CMake project)?

**Comment by remi-moyen** [comment]
Your link is part of the same page as the one I posted so I guess we found the same solution!

Visual Studio handles CMake projects correctly without any plugin (or rather, CMake can generate Visual Projects correctly when running e.g. `cmake -G "Visual Studio 17 2022"` though this is the default on Windows so this isn't really needed). But, as the link mentions, the headers need to be in the `${SOURCES}` for them to be listed as part of the project itself (rather than as external dependencies).

So my fix was to do exactly that, adding the headers to `${SOURCES}`. This works for me (Visual Studio) and I don't think this should have any negative effect in other development environments? But I haven't tested (on Linux I just use the command line, no IDE).

If my fix causes problems with other IDEs, then it should be easy to wrap the code that I added in a specific `IF()` based on detecting the generator used (`${CMAKE_GENERATOR}` although there are several generators for Visual Studio so a bit of regexp matching would be needed to find if the variable contains "Visual Studio" -- there may be a simpler way?).

**Comment by remi-moyen** [comment]
After discussing with Fabien, here's another fix.

The idea of the `all_includes.cmake` file was to avoid using `GLOB` to list files, which isn't recommended as it can cause CMake to not know about added/removed files. However explicitly listing files requiring updating that list manually, which is tedious. Here, since the list is only used to help Visual Studio build the project tree (it is not needed to compile the code), using `GLOB` isn't really an issue (at worst, the project tree in Visual Studio will be slightly out of date but even that doesn't prevent browsing the file, it's just that it will be shown as an "external" include).

So the new fix uses `GLOB` to avoid listing the includes. Which means we no longer need an additional file, the whole fix is small-enough to be directly into `cpp.cmake`.

Also, to make sure this fix does not have any impact on other IDEs (it should not, but just in case), the fix is restricted to Visual Studio with an `IF()`.
