### ISSUE TITLE
Varz bug : wrong values

### ISSUE THREAD

**Issue by Antoine-Chim** [gstlearn/gstlearn#270]
Hello,

I am working with Python and gstlearn, and I have a problem with the flag_varz=True function that I am using with kriging like this:
err = gl.kriging(dbin=db, dbout=grid, model=fitmod, 
              neigh=uniqueNeigh,
              flag_est=True, flag_std=True, flag_varz=True
              )
The kriging variance is being calculated correctly, but I think there might be a bug. Specifically, the maximum values are around the points, while the minimum values are in the areas without points, which should be the other way around if I'm not too rusty. There is no issue with the standard deviation (flag_std).

Thank you in advance.
![image](https://github.com/user-attachments/assets/12b65534-f1dd-4f4d-827b-6d86d57d2139)
![image](https://github.com/user-attachments/assets/cbf163ab-347c-4f8e-b433-2a1b3eae870e)

**Comment by NDesassis** [comment]
Dear Antoine, 

Thank you for your message. The option flag_varz allows to compute the variance of the estimator of Z (Var(Z*)) which has no reason to be smaller near the data. The kriging standard deviation computes the square-root of Var(Z*-Z), which is smaller around the data. Var(Z*) is not often used. It is mainly computed to apply some methods of non-linear geostatistics (e.g uniform conditioning).
I hope this message helps you.
Regards,
Nicolas
