### ISSUE TITLE
Problème fonction  Model::computeLogLikelihood 	

### ISSUE THREAD

**Issue by mike-pereira** [gstlearn/gstlearn#273]
Hello,
Je rencontre un problème lorsque j'utilise la fonction  Model::computeLogLikelihood pour calculer la vraissemblance d'un modèle ne comportant pas de drift par rapport à des données.
Problème: Kernel crash
Cause possible: La fonction esssaie de faire des calculs avec une matrice de drift qui n'est pas définie (car il n'y a pas de drift dans le modèle)
Code pour reproduire le problème en Python:
```
import gstlearn as gl

## Créer des données
dat=gl.Db_createFillRandom(100)

## Créer un modèle
mdl = gl.Model()
mdl.addCovFromParam(gl.ECov.CUBIC,20,1)
# mdl.addDrift(gl.DriftM()) #<- Décommenter pour faire marcher le code

## Calculer la vraissemblance
driftMat=mdl.evalDriftMatrix(dat).toTL() #<- fonctionne mais retourne une matrice vide
mdl.computeLogLikelihood(dat,verbose=True)  #<--- Crash
```
Merci la team!

**Comment by drenard77810** [comment]
This is now permitted in the calculation of Model::computeLogLikelihood.
The current status is:
- if you do not attach any drift vector in the Model, then the LogLikelihood is calculated considering that the data should be centered using the constant mean value(s) stored in the Model
- as you as you attach one or several drift functions to the Model, the profiled LogLikelihood is calculated instead: i.e. the optimal coefficients of the drift functions are calculated first; then the data are centered by removing this "optimal" drift prior to calculation of LogLikelihood
