### ISSUE TITLE
Wrong number of "codes" in Db::createFillRandom

### ISSUE THREAD

**Issue by fabien-ors** [gstlearn/gstlearn#274]
When executing (in R) the following instructions, the 'code' variable has 6 unique values {0, 1, 2, 3, 4, 5} in place of ncode = 5
```
library(gstlearn)
db = Db_createFillRandom(100, ncode = 5)
unique(db['code'])
```
This returns:
`[1] 1 5 2 4 3 0`

**Comment by drenard77810** [comment]
This is now fixed
