### ISSUE TITLE
Allow code using gstlearn to use #include<gstlearn/...>

### ISSUE THREAD

**Issue by remi-moyen** [gstlearn/gstlearn#319]
Currently when a (C++) project wants to use gstlearn, the includes must be specified as e.g.:
```C++
#include <API/SPDE.hpp>
```

However when using many libraries it is not very clean to *not* see in the name that this is an include for gstlearn. In this example `SPDE.hpp` is pretty unique but with common names such as `Model/Model.hpp` or, worse, `version.h`, it is not hard to see how that could create conflicts with other libraries.

It would therefore be better to have the possibility to specify instead:
```C++
#include <gstlearn/API/SPDE.hpp>
```

Since in the install directories the includes are already in `include/gstlearn` this can easily be achieved by changing `install.cmake`:
https://github.com/gstlearn/gstlearn/blob/97dc47ec90fb96b935ab90e4f4907898159cde6a/cmake/install.cmake#L24-L28
by adding the `include` directory itself in the include directories:
```CMake
# Include directories
target_include_directories(shared PUBLIC
  # Installed includes are made PUBLIC for client who links the shared library
  $<INSTALL_INTERFACE:include/${PROJECT_NAME}>
  $<INSTALL_INTERFACE:include>
)
```

My personal taste would be to entirely remove the first one (`include/${PROJECT_NAME}`) to force the use of `#include <gstlearn/...>` but doing so would break all existing code (including all internal includes inside gstlearn itself!) and is a matter of personal choice, so I don't think it's a good idea. Adding an additional accepted include path, however, allows using `#include <gstlearn/...>` and has no downside.

Note that this is somewhat related to #108 in that they're both to make the use of gstlearn in complex projects cleaner. But this one is easy to solve!

**Comment by pierre-guillou** [comment]
You raised a valid point here but I'm a bit concerned about exposing the whole `$prefix/include` directory to gstlearn consumers. I looked at Eigen and VTK and they don't seem to follow this route. In particular, Eigen puts all its headers into an `Eigen` subfolder of the `$prefix/include/eigen3` directory, while VTK prefixes all its headers with `vtk` to not confuse users.

Renaming all gstlearn headers seems too complex for now. Should we rather do like Eigen and put our headers in another subfolder: `$prefix/include/gstlearn/gstlearn` and make CMake expose the outer `gstlearn` directory?

Note: replacing `$<INSTALL_INTERFACE:include/${PROJECT_NAME}>` with ` $<INSTALL_INTERFACE:include>` should not break gstlearn's compilation, since the build process will use ` $<BUILD_INTERFACE: ${INCLUDES}>` (cpp.cmake) instead.

**Comment by remi-moyen** [comment]
I don't really see what is the issue with exposing `$prefix/include` rather than `$prefix/include/gstlearn`, as the former does not contain anything else than `gstlearn/`. I guess if you were to use e.g. `/usr` as `$prefix` this means including gstlearn would add `-I/usr/include`? That doesn't seem a very big concern to me.

Still, either of the other two suggestions (prefix everything or move everything in `$prefix/include/gstlearn/gstlearn` would work as far as I'm concerned (i.e. to ensure that gstlearn includes cannot be confused with other libraries), so I don't mind those.

I agree that renaming everything is a bit of work, so the second approach (like Eigen) is good for me.

It would be a bit weird looking at the directory structure (`$prefix/include/gstlearn` would contain nothing else than another directory called `gstlearn` again) but this is purely cosmetic so not really an issue.

So I guess the proposed solution would be to change the `target_include_directories` to (I haven't tested):
```CMake
# Include directories
target_include_directories(shared PUBLIC
  # Installed includes are made PUBLIC for client who links the shared library
  $<INSTALL_INTERFACE:include/${PROJECT_NAME}/${PROJECT_NAME}>
)

[...]

# Install the includes
install(
  DIRECTORY   ${INCLUDES}
  DESTINATION include/${PROJECT_NAME}/${PROJECT_NAME}
)

# Install the export header file
install(FILES ${PROJECT_BINARY_DIR}/${PROJECT_NAME}_export.hpp
        DESTINATION include/${PROJECT_NAME}/${PROJECT_NAME}
)

# Install the version header file
install(
  FILES ${PROJECT_BINARY_DIR}/version.h
  DESTINATION include/${PROJECT_NAME}/${PROJECT_NAME}
)
```
