### ISSUE TITLE
Generated CMake package contains hard-coded paths to the source code

### ISSUE THREAD

**Issue by remi-moyen** [gstlearn/gstlearn#326]
When installing gstlearn with `make install` (or the INSTALL target in Visual Studio), a CMake package is generated with file `<install_dir>/share/gstlearn/cmake/gstlearnTargets.cmake`. This allows using `find_package()` and then just the target `gstlearn::shared` in other libraries using it.

However `gstlearnTargets.cmake` contains a reference to the path to the source code, in my case `D:/Dev/sandbox/gstlearn`:
```CMake
set_target_properties(gstlearn::shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Dev/sandbox/gstlearn/;D:/Dev/sandbox/gstlearn/;${_IMPORT_PREFIX}/include/gstlearn;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen;iphlpapi;rpcrt4"
)
```

This is because in `cpp.cmake` the `target_include_directories()` are specified as `PUBLIC` which means they are part of the "interface" of the target (see [CMake's doc](https://cmake.org/cmake/help/latest/command/target_include_directories.html)).

The issue is that when the package is then copied to a computer that does not have the source code (i.e. those paths are invalid), CMake fails to load the package:
```CMake
CMake Error in /data/<snip>/src/Core/CMakeLists.txt:
  Imported target "gstlearn::shared" includes non-existent path

    "D:/Dev/sandbox/gstlearn/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

Setting the `target_include_directories()` to `PRIVATE` fixes this as the generated `gstlearnTargets.cmake` becomes:
```CMake
set_target_properties(gstlearn::shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gstlearn;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen;iphlpapi;rpcrt4"
)
```

So this is the change I have made in my version.

However in `cpp.cmake` there is a comment saying that there is a good reason for the includes to be `PUBLIC` (for tests), so I don't know if setting them `PRIVATE` will cause issues there. Still, the way they are currently set is definitely wrong as we end up with hard-coded paths in the package.

**Comment by remi-moyen** [comment]
I am however confused about why the original code (with `PUBLIC`) doesn't work. The command in `cpp.cmake` uses the `BUILD_INTERFACE` generator expression so it should not be exported by `install(EXPORT)`. At least this is how I understand the documentation of those commands.

So it is possible that this issue could be fixed in `install.cmake` by somehow making it clear that when installing, only the `INSTALL_INTERFACE` paths should be used. Which I thought was the default, but maybe not?

Another related thing is that `cpp.cmake` uses `export()` to create a local file (in the build tree) called `gstlearn.cmake`, which defines a local target. Shouldn't the tests use this file to properly define the target? (and maybe then they would get the include paths right) Then again, the tests (e.g. in `tests/data/CMakeLists.txt`) are clearly already aware of the `${PROJECT_NAME}::shared` target since they use that with `target_link_libraries()` so...?

I'm probably confused about how CMake works, and reading CMake's doc doesn't help a lot, this may be all wrong...

**Comment by remi-moyen** [comment]
Sorry for spamming this issue, this is looking more like a notepad than a proper report... I think I've got it now!

Anyway, after searching a bit more I found [this discussion](https://discourse.cmake.org/t/how-to-install-export-target-with-install-interface/5293) which looks like the same issue (`BUILD_INTERFACE` includes are copied into an install file), and the issue seems relevant as indeed in `cpp.cmake` the strings are not protected.

After changing `cpp.cmake` to the following:
```CMake
target_include_directories(${FLAVOR} PUBLIC
    # Add includes path for compiling the library
    "$<BUILD_INTERFACE:${INCLUDES}>"
    # Add binary directory to find generated version.h and export.hpp
    "$<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>"
  )
```
(note that I have also removed spaces between `BUILD_INTERFACE:` and the following `$`!)

Then now the generated package `gstlearnTargets.cmake` no longer contains hard-coded paths to the source tree, and the tests compile correctly without changing their CMakeLists.txt.

So I think this is the correct solution?

(note that you may want to also change `install.cmake` to use quotes around the `INSTALL_INTERFACE` paths since apparently that matters?)

**Comment by pierre-guillou** [comment]
Thanks for reporting this issue and pointing where to fix it!

I noticed these build paths in `gstlearnTargets.cmake` when testing for #319 but didn't look much on them. I didn't think nonexistent include paths could lead to build errors.

I tested your proposed changes on my local machine. It seems that the fix consists only in removing the space after the `:`. The double quotes don't have any impact on the generated `gstlearnTargets.cmake` file. 

With double quotes and the space, CMake fails with an error. The double quotes should be used to prevent that.

**Comment by remi-moyen** [comment]
Indeed, the quotes are probably not needed once the space is removed.

Still, I wonder if quotes are not better. What happens for example if `${INCLUDES}` or `${PROJECT_BINARY_DIR}` contains a space, is that handled correctly?

But I truly don't understand enough of CMake to know what's best, so if just removing the space is enough, I'm fine with that.
