### ISSUE TITLE
crash when adjusting a model with [J_bessel, K_bessel, Gamma]

### ISSUE THREAD

**Issue by tromary** [gstlearn/gstlearn#98]
call to model.fit causes the crash of the Python kernel...
BTW what is the Gamma covariance ?

**Comment by tromary** [comment]
Thanks for the answer, unfortunately I do not have the script, as a student encountered this error. It occurs that I am not able to reproduce it. As I remember, it was just a call to fitmod.fit but : 
"err = fitmod.fit(varioexp,types = [gl.ECov.BESSEL_J,gl.ECov.BESSEL_K,gl.ECov.GAMMA])"
works fine for me on the same dataset...

**Comment by drenard77810** [comment]
The bug has finally been reproduced.
The GAMMA function calculates the coefficient for transforming theoretical range to practical range.
This coefficient is set to pow(20, 1/param) - 1
When param gets too small, this provoked either a message or a crash. 
The code has been made more robust.
Will be delivered in next release.
